### ISSUE TITLE
Proxy mission option

### ISSUE THREAD

**Issue by chi110r** [matgou/ZabbixWebScenarioBuilder#1]
Hi,
when i start this, i get  the following error:

> 2021-11-16 09:51:02,604 - root - INFO - Start ZabbixWebScenarioBuilder (v1.0.0)
> 2021-11-16 09:51:02,604 - root - DEBUG - Load config from config.ini
> 2021-11-16 09:51:02,605 - root - INFO - Démarage du serveur proxy sur 127.0.0.1:3128
> Exception in thread Thread-1:
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
>     self.run()
>   File "/usr/lib/python3.8/threading.py", line 870, in run
>     self._target(*self._args, **self._kwargs)
>   File "/home/andreas/git-dir/Linux/monitoring/ZabbixWebScenarioBuilder/proxy/captive_proxy.py", line 209, in start_proxy
>     self.run(CaptiveProxyDumper, cmdline.mitmdump, args, extra)
>   File "/home/andreas/git-dir/Linux/monitoring/ZabbixWebScenarioBuilder/proxy/captive_proxy.py", line 150, in run
>     if pconf.options.server:
> AttributeError: 'NoneType' object has no attribute 'options'
> 2021-11-16 09:51:03,612 - root - INFO - fix config
> 2021-11-16 09:51:03,612 - root - INFO - Connexion au serveur https://*******.net/zabbix
> 2021-11-16 09:51:04,038 - root - INFO - Démarage du serveur d api
> 2021-11-16 09:51:05,132 - root - INFO - Start websocket server : localhost:3130
> 2021-11-16 09:51:05,149 - websockets.server - INFO - server listening on 127.0.0.1:3130
> 

OS: Ubuntu 20.04 in WLS2

**Comment by alexc34470** [comment]
Hello, i have the same error, did you succeed to resolve the problem ? 
Thx

**Comment by chi110r** [comment]
@alexc34470 No i just tried it, it fails and i reportetd it. i am notreally good in python
